import { Button, Flex, Heading, Input, Link, useColorMode } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { MouseEventHandler, useCallback } from 'react'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  const router = useRouter()

  const handleMouseEvent = (path: string) => {
    
    router.push(path)
  };

  return (
    <div>
      <Head>
        <title>Calculadora de Notas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <Flex height="90vh" alignItems="center" justifyContent="center" marginX={4}>
        <Flex direction="column" backgroundColor="gray.200" p={12} rounded={6} >
          <Heading mb={6} textAlign='center'>
            Calculadora de Notas
          </Heading>
          <Button 
            onClick={() => handleMouseEvent('baiana')} 
            colorScheme="teal" 
            name="baiana"
            margin={2}
          >
            Baiana
          </Button>
          <Button 
            onClick={() => handleMouseEvent('senai')}
            colorScheme="teal"
            name="baiana"
            margin={2}
          >
            Senai
          </Button>
        </Flex>
      </Flex>
      <Footer />
    </div>
  )
}

export default Home
