import { Button, Flex, Heading, Input } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Senai: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Senai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <Flex height="100vh" alignItems="center" justifyContent="center">
        <Flex direction="column" backgroundColor="gray.100" p={12} rounded={6}>
          <Heading mb={6}>
            Senai
          </Heading>
        </Flex>
      </Flex>
       
    </div>
  )
}

export default Senai
